import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { CartModalProvider } from './context/CartSidebarModalContext';
import { ReduxProvider } from './redux/provider';
import { ModalProvider } from './context/QuickViewModalContext';
import { PreviewSliderProvider } from './context/PreviewSliderContext';
import CartSidebarModal from '@/components/CartSidebarModal';
import Navbar from '@/components/Header';
import { SessionProvider } from 'next-auth/react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'HNQ Store',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <CartModalProvider>
            <ModalProvider>
              <PreviewSliderProvider>
                <SessionProvider>
                  <Navbar/>
                  {children}
                </SessionProvider>

                <CartSidebarModal />
              </PreviewSliderProvider>
            </ModalProvider>
          </CartModalProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
